"""Jeu de données du référentiel biologique (valeurs de référence).

Transcription fidèle du référentiel fourni (IFCC/Tietz, ADA/OMS, ESC/EAS,
KDIGO, OMS spermogramme…). Chaque entrée : code, nom, catégorie, prélèvement,
sexe, tranche d'âge, bornes normales, unité, texte normal (qualitatif),
seuils critiques, interprétation, source.
"""

from __future__ import annotations


def _r(
    test_code: str,
    test_name: str,
    category: str,
    specimen: str,
    sex: str,
    amin: float,
    amax: float,
    lo: float | None,
    hi: float | None,
    unit: str,
    normal_text: str | None,
    clo: float | None,
    chi: float | None,
    interp: str,
    source: str,
) -> dict:
    return {
        "test_code": test_code,
        "test_name": test_name,
        "category": category,
        "specimen": specimen,
        "sex": sex,
        "age_min_years": amin,
        "age_max_years": amax,
        "lower_limit": lo,
        "upper_limit": hi,
        "unit": unit,
        "normal_text": normal_text,
        "critical_low": clo,
        "critical_high": chi,
        "interpretation": interp,
        "source": source,
    }


BIOREF_SEED: list[dict] = [
    # ── HÉMATOLOGIE ──────────────────────────────────────────────────────────
    _r(
        "HB",
        "Hémoglobine",
        "Hématologie",
        "Sang total EDTA",
        "Homme",
        15,
        120,
        13,
        17,
        "g/dL",
        None,
        7,
        20,
        "Anémie si basse ; polyglobulie si élevée",
        "IFCC/Tietz/usage laboratoire",
    ),
    _r(
        "HB",
        "Hémoglobine",
        "Hématologie",
        "Sang total EDTA",
        "Femme",
        15,
        120,
        12,
        16,
        "g/dL",
        None,
        7,
        20,
        "Anémie si basse ; polyglobulie si élevée",
        "IFCC/Tietz/usage laboratoire",
    ),
    _r(
        "HT",
        "Hématocrite",
        "Hématologie",
        "Sang total EDTA",
        "Homme",
        15,
        120,
        40,
        52,
        "%",
        None,
        20,
        None,
        "Diminué dans les anémies ; augmenté dans la déshydratation/polyglobulie",
        "IFCC/Tietz",
    ),
    _r(
        "HT",
        "Hématocrite",
        "Hématologie",
        "Sang total EDTA",
        "Femme",
        15,
        120,
        36,
        48,
        "%",
        None,
        20,
        None,
        "Diminué dans les anémies ; augmenté dans la déshydratation/polyglobulie",
        "IFCC/Tietz",
    ),
    _r(
        "WBC",
        "Leucocytes",
        "Hématologie",
        "Sang total EDTA",
        "ALL",
        0,
        120,
        4,
        10,
        "10*9/L",
        None,
        1,
        50,
        "Leucopénie si bas ; hyperleucocytose si élevé",
        "IFCC/Tietz",
    ),
    _r(
        "PLT",
        "Plaquettes",
        "Hématologie",
        "Sang total EDTA",
        "ALL",
        0,
        120,
        150,
        400,
        "10*9/L",
        None,
        20,
        1000,
        "Risque hémorragique si très bas ; thrombocytose si élevé",
        "IFCC/Tietz",
    ),
    _r(
        "RBC_H",
        "Globules rouges",
        "Hématologie",
        "Sang total EDTA",
        "Homme",
        15,
        120,
        4.5,
        5.9,
        "10*12/L",
        None,
        None,
        None,
        "À interpréter avec Hb, Ht et indices érythrocytaires",
        "IFCC/Tietz",
    ),
    _r(
        "RBC_F",
        "Globules rouges",
        "Hématologie",
        "Sang total EDTA",
        "Femme",
        15,
        120,
        4.0,
        5.2,
        "10*12/L",
        None,
        None,
        None,
        "À interpréter avec Hb, Ht et indices érythrocytaires",
        "IFCC/Tietz",
    ),
    _r(
        "MCV",
        "VGM",
        "Hématologie",
        "Sang total EDTA",
        "ALL",
        15,
        120,
        80,
        100,
        "fL",
        None,
        None,
        None,
        "Microcytose si bas ; macrocytose si élevé",
        "IFCC/Tietz",
    ),
    _r(
        "MCH",
        "TCMH",
        "Hématologie",
        "Sang total EDTA",
        "ALL",
        15,
        120,
        27,
        32,
        "pg",
        None,
        None,
        None,
        "Diminué dans les anémies hypochromes",
        "IFCC/Tietz",
    ),
    _r(
        "MCHC",
        "CCMH",
        "Hématologie",
        "Sang total EDTA",
        "ALL",
        15,
        120,
        32,
        36,
        "g/dL",
        None,
        None,
        None,
        "Indice de concentration corpusculaire en Hb",
        "IFCC/Tietz",
    ),
    # ── FORMULE LEUCOCYTAIRE ─────────────────────────────────────────────────
    _r(
        "NEUT_PCT",
        "Neutrophiles",
        "Formule leucocytaire",
        "Sang total EDTA",
        "ALL",
        15,
        120,
        40,
        75,
        "%",
        None,
        None,
        None,
        "Neutrophilie souvent infectieuse bactérienne/inflammatoire",
        "IFCC/Tietz",
    ),
    _r(
        "LYMPH_PCT",
        "Lymphocytes",
        "Formule leucocytaire",
        "Sang total EDTA",
        "ALL",
        15,
        120,
        20,
        45,
        "%",
        None,
        None,
        None,
        "Lymphocytose souvent virale ou réactionnelle",
        "IFCC/Tietz",
    ),
    _r(
        "MONO_PCT",
        "Monocytes",
        "Formule leucocytaire",
        "Sang total EDTA",
        "ALL",
        15,
        120,
        2,
        10,
        "%",
        None,
        None,
        None,
        "Monocytose possible dans infections chroniques/inflammation",
        "IFCC/Tietz",
    ),
    _r(
        "EOS_PCT",
        "Éosinophiles",
        "Formule leucocytaire",
        "Sang total EDTA",
        "ALL",
        15,
        120,
        1,
        6,
        "%",
        None,
        None,
        None,
        "Éosinophilie : allergie, parasitose, dermatose",
        "IFCC/Tietz",
    ),
    _r(
        "BASO_PCT",
        "Basophiles",
        "Formule leucocytaire",
        "Sang total EDTA",
        "ALL",
        15,
        120,
        0,
        2,
        "%",
        None,
        None,
        None,
        "Rarement isolé ; interprétation contextuelle",
        "IFCC/Tietz",
    ),
    # ── BIOCHIMIE : GLYCÉMIE ─────────────────────────────────────────────────
    _r(
        "GLU_FAST",
        "Glycémie à jeun",
        "Biochimie",
        "Plasma fluoré ou sérum",
        "ALL",
        0,
        120,
        0.70,
        1.10,
        "g/L",
        None,
        0.40,
        4.00,
        "Hypoglycémie si basse ; diabète à confirmer si ≥1,26 g/L à jeun à deux reprises",
        "ADA/OMS/usage labo",
    ),
    _r(
        "GLU_PP",
        "Glycémie post-prandiale",
        "Biochimie",
        "Plasma fluoré ou sérum",
        "ALL",
        0,
        120,
        None,
        1.40,
        "g/L",
        "< 1,40 g/L",
        0.40,
        4.00,
        "Hyperglycémie post-prandiale si élevée",
        "ADA/OMS",
    ),
    _r(
        "HBA1C",
        "HbA1c",
        "Biochimie",
        "Sang total EDTA",
        "ALL",
        0,
        120,
        None,
        5.7,
        "%",
        "< 5,7 %",
        None,
        None,
        "Normal <5,7 ; prédiabète 5,7–6,4 ; diabète ≥6,5",
        "ADA/OMS",
    ),
    # ── FONCTION RÉNALE ──────────────────────────────────────────────────────
    _r(
        "CREAT",
        "Créatinine",
        "Biochimie rénale",
        "Sérum ou plasma",
        "Homme",
        15,
        120,
        7,
        13,
        "mg/L",
        None,
        None,
        30,
        "À interpréter avec le DFG estimé",
        "IFCC/Tietz",
    ),
    _r(
        "CREAT",
        "Créatinine",
        "Biochimie rénale",
        "Sérum ou plasma",
        "Femme",
        15,
        120,
        6,
        11,
        "mg/L",
        None,
        None,
        30,
        "À interpréter avec le DFG estimé",
        "IFCC/Tietz",
    ),
    _r(
        "UREA",
        "Urée",
        "Biochimie rénale",
        "Sérum ou plasma",
        "ALL",
        0,
        120,
        0.15,
        0.45,
        "g/L",
        None,
        None,
        2.00,
        "Élevée dans insuffisance rénale, déshydratation, hypercatabolisme",
        "IFCC/Tietz",
    ),
    _r(
        "EGFR",
        "DFG estimé",
        "Biochimie rénale",
        "Calculé",
        "ALL",
        18,
        120,
        90,
        None,
        "mL/min/{1.73_m2}",
        "> 90",
        None,
        None,
        "DFG <60 pendant ≥3 mois évoque maladie rénale chronique",
        "KDIGO",
    ),
    _r(
        "URIC_H",
        "Acide urique",
        "Biochimie rénale",
        "Sérum",
        "Homme",
        15,
        120,
        35,
        70,
        "mg/L",
        None,
        None,
        None,
        "Hyperuricémie : goutte, syndrome métabolique, insuffisance rénale",
        "IFCC/Tietz",
    ),
    _r(
        "URIC_F",
        "Acide urique",
        "Biochimie rénale",
        "Sérum",
        "Femme",
        15,
        120,
        25,
        60,
        "mg/L",
        None,
        None,
        None,
        "Hyperuricémie : goutte, syndrome métabolique, insuffisance rénale",
        "IFCC/Tietz",
    ),
    # ── IONOGRAMME ───────────────────────────────────────────────────────────
    _r(
        "NA",
        "Sodium",
        "Ionogramme",
        "Sérum ou plasma",
        "ALL",
        0,
        120,
        135,
        145,
        "mmol/L",
        None,
        120,
        160,
        "Hyponatrémie ou hypernatrémie selon valeur",
        "IFCC/Tietz",
    ),
    _r(
        "K",
        "Potassium",
        "Ionogramme",
        "Sérum ou plasma",
        "ALL",
        0,
        120,
        3.5,
        5.0,
        "mmol/L",
        None,
        2.5,
        6.5,
        "Trouble potentiellement grave du rythme cardiaque",
        "IFCC/Tietz",
    ),
    _r(
        "CL",
        "Chlore",
        "Ionogramme",
        "Sérum ou plasma",
        "ALL",
        0,
        120,
        98,
        107,
        "mmol/L",
        None,
        None,
        None,
        "À interpréter avec sodium, bicarbonates et équilibre acido-basique",
        "IFCC/Tietz",
    ),
    _r(
        "CA",
        "Calcium total",
        "Ionogramme",
        "Sérum",
        "ALL",
        0,
        120,
        2.20,
        2.60,
        "mmol/L",
        None,
        1.75,
        3.50,
        "Corriger selon albumine si nécessaire",
        "IFCC/Tietz",
    ),
    _r(
        "MG",
        "Magnésium",
        "Ionogramme",
        "Sérum",
        "ALL",
        0,
        120,
        0.70,
        1.05,
        "mmol/L",
        None,
        None,
        None,
        "Troubles neuromusculaires ou cardiaques possibles",
        "IFCC/Tietz",
    ),
    # ── BILAN HÉPATIQUE ──────────────────────────────────────────────────────
    _r(
        "AST",
        "ASAT / TGO",
        "Bilan hépatique",
        "Sérum",
        "ALL",
        0,
        120,
        None,
        40,
        "[IU]/L",
        "< 40 [IU]/L",
        None,
        1000,
        "Cytolyse hépatique, musculaire ou cardiaque possible",
        "IFCC/Tietz",
    ),
    _r(
        "ALT",
        "ALAT / TGP",
        "Bilan hépatique",
        "Sérum",
        "ALL",
        0,
        120,
        None,
        40,
        "[IU]/L",
        "< 40 [IU]/L",
        None,
        1000,
        "Plus spécifique du foie que ASAT",
        "IFCC/Tietz",
    ),
    _r(
        "GGT",
        "Gamma-GT",
        "Bilan hépatique",
        "Sérum",
        "Homme",
        15,
        120,
        None,
        55,
        "[IU]/L",
        "< 55 [IU]/L",
        None,
        None,
        "Cholestase, alcool, médicaments, stéatose",
        "IFCC/Tietz",
    ),
    _r(
        "GGT",
        "Gamma-GT",
        "Bilan hépatique",
        "Sérum",
        "Femme",
        15,
        120,
        None,
        38,
        "[IU]/L",
        "< 38 [IU]/L",
        None,
        None,
        "Cholestase, alcool, médicaments, stéatose",
        "IFCC/Tietz",
    ),
    _r(
        "ALP",
        "Phosphatases alcalines",
        "Bilan hépatique",
        "Sérum",
        "ALL",
        15,
        120,
        40,
        130,
        "[IU]/L",
        None,
        None,
        None,
        "Cholestase ou origine osseuse possible",
        "IFCC/Tietz",
    ),
    _r(
        "BILT",
        "Bilirubine totale",
        "Bilan hépatique",
        "Sérum",
        "ALL",
        0,
        120,
        None,
        17,
        "µmol/L",
        "< 17 µmol/L",
        None,
        None,
        "Ictère biologique si élevée",
        "IFCC/Tietz",
    ),
    _r(
        "BILD",
        "Bilirubine conjuguée",
        "Bilan hépatique",
        "Sérum",
        "ALL",
        0,
        120,
        None,
        5,
        "µmol/L",
        "< 5 µmol/L",
        None,
        None,
        "Élevée en cholestase ou atteinte hépatocellulaire",
        "IFCC/Tietz",
    ),
    # ── INFLAMMATION / PROTÉINES ─────────────────────────────────────────────
    _r(
        "CRP",
        "CRP",
        "Inflammation",
        "Sérum",
        "ALL",
        0,
        120,
        None,
        6,
        "mg/L",
        "< 6 mg/L",
        None,
        200,
        "Marqueur inflammatoire non spécifique",
        "IFCC/Tietz",
    ),
    _r(
        "TPROT",
        "Protéines totales",
        "Protéines",
        "Sérum",
        "ALL",
        0,
        120,
        65,
        85,
        "g/L",
        None,
        None,
        None,
        "Hypoprotidémie ou hyperprotidémie selon contexte",
        "IFCC/Tietz",
    ),
    _r(
        "ALB",
        "Albumine",
        "Protéines",
        "Sérum",
        "ALL",
        0,
        120,
        35,
        50,
        "g/L",
        None,
        25,
        None,
        "Dénutrition, inflammation, pertes rénales ou hépatiques si basse",
        "IFCC/Tietz",
    ),
    # ── LIPIDES ──────────────────────────────────────────────────────────────
    _r(
        "CHOL_T",
        "Cholestérol total",
        "Bilan lipidique",
        "Sérum",
        "ALL",
        0,
        120,
        None,
        2.00,
        "g/L",
        "< 2,00 g/L",
        None,
        None,
        "Interprétation selon risque cardiovasculaire",
        "ESC/EAS/usage labo",
    ),
    _r(
        "LDL",
        "LDL-cholestérol",
        "Bilan lipidique",
        "Sérum",
        "ALL",
        0,
        120,
        None,
        1.30,
        "g/L",
        "< 1,30 g/L",
        None,
        None,
        "Objectif variable selon risque cardiovasculaire",
        "ESC/EAS",
    ),
    _r(
        "HDL",
        "HDL-cholestérol",
        "Bilan lipidique",
        "Sérum",
        "Homme",
        15,
        120,
        0.40,
        None,
        "g/L",
        "> 0,40 g/L",
        None,
        None,
        "HDL bas = facteur de risque cardiovasculaire",
        "ESC/EAS",
    ),
    _r(
        "HDL",
        "HDL-cholestérol",
        "Bilan lipidique",
        "Sérum",
        "Femme",
        15,
        120,
        0.50,
        None,
        "g/L",
        "> 0,50 g/L",
        None,
        None,
        "HDL bas = facteur de risque cardiovasculaire",
        "ESC/EAS",
    ),
    _r(
        "TG",
        "Triglycérides",
        "Bilan lipidique",
        "Sérum",
        "ALL",
        0,
        120,
        None,
        1.50,
        "g/L",
        "< 1,50 g/L",
        None,
        10,
        "Hypertriglycéridémie ; risque pancréatite si très élevé",
        "ESC/EAS",
    ),
    # ── COAGULATION ──────────────────────────────────────────────────────────
    _r(
        "PT",
        "Taux de prothrombine",
        "Coagulation",
        "Plasma citrate",
        "ALL",
        0,
        120,
        70,
        100,
        "%",
        None,
        None,
        None,
        "Explore la voie extrinsèque de la coagulation",
        "IFCC/Tietz",
    ),
    _r(
        "INR",
        "INR",
        "Coagulation",
        "Plasma citrate",
        "ALL",
        0,
        120,
        0.8,
        1.2,
        "",
        None,
        None,
        5,
        "Surveillance AVK selon cible thérapeutique",
        "IFCC/Tietz",
    ),
    _r(
        "APTT",
        "TCA ratio",
        "Coagulation",
        "Plasma citrate",
        "ALL",
        0,
        120,
        0.8,
        1.2,
        "ratio",
        None,
        None,
        None,
        "Explore la voie intrinsèque de la coagulation",
        "IFCC/Tietz",
    ),
    _r(
        "FIB",
        "Fibrinogène",
        "Coagulation",
        "Plasma citrate",
        "ALL",
        0,
        120,
        2,
        4,
        "g/L",
        None,
        1,
        None,
        "Baisse : risque hémorragique ; hausse : inflammation",
        "IFCC/Tietz",
    ),
    # ── PALUDISME ────────────────────────────────────────────────────────────
    _r(
        "MAL_GE",
        "Goutte épaisse",
        "Parasitologie",
        "Sang capillaire ou EDTA",
        "ALL",
        0,
        120,
        None,
        None,
        "",
        "Négatif",
        None,
        None,
        "Positif = paludisme confirmé ; quantifier si possible",
        "OMS/usage labo",
    ),
    _r(
        "MAL_TDR",
        "TDR Paludisme",
        "Parasitologie",
        "Sang capillaire ou EDTA",
        "ALL",
        0,
        120,
        None,
        None,
        "",
        "Négatif",
        None,
        None,
        "Interpréter selon clinique et goutte épaisse si disponible",
        "OMS/usage labo",
    ),
    # ── SÉROLOGIES ───────────────────────────────────────────────────────────
    _r(
        "HIV",
        "VIH 1/2",
        "Sérologie",
        "Sérum ou plasma",
        "ALL",
        0,
        120,
        None,
        None,
        "",
        "Négatif",
        None,
        None,
        "Tout résultat positif doit suivre l'algorithme national de confirmation",
        "OMS/PNLS",
    ),
    _r(
        "HBSAG",
        "Ag HBs",
        "Sérologie",
        "Sérum ou plasma",
        "ALL",
        0,
        120,
        None,
        None,
        "",
        "Négatif",
        None,
        None,
        "Positif = infection VHB actuelle à confirmer/évaluer",
        "OMS/usage labo",
    ),
    _r(
        "HCV_AB",
        "Ac anti-VHC",
        "Sérologie",
        "Sérum ou plasma",
        "ALL",
        0,
        120,
        None,
        None,
        "",
        "Négatif",
        None,
        None,
        "Positif = contact VHC ; confirmer par ARN VHC si disponible",
        "OMS/usage labo",
    ),
    _r(
        "VDRL",
        "VDRL",
        "Sérologie syphilis",
        "Sérum",
        "ALL",
        0,
        120,
        None,
        None,
        "",
        "Négatif",
        None,
        None,
        "Test non tréponémique ; interpréter avec TPHA",
        "OMS/usage labo",
    ),
    _r(
        "TPHA",
        "TPHA",
        "Sérologie syphilis",
        "Sérum",
        "ALL",
        0,
        120,
        None,
        None,
        "",
        "Négatif",
        None,
        None,
        "Test tréponémique ; interpréter avec VDRL",
        "OMS/usage labo",
    ),
    # ── GROSSESSE ────────────────────────────────────────────────────────────
    _r(
        "BHCG_QUAL",
        "β-HCG qualitatif",
        "Grossesse",
        "Urines ou sérum",
        "Femme",
        10,
        60,
        None,
        None,
        "",
        "Négatif",
        None,
        None,
        "Positif compatible avec grossesse selon contexte",
        "Usage labo",
    ),
    _r(
        "BHCG_QUANT",
        "β-HCG quantitatif",
        "Grossesse",
        "Sérum",
        "Femme",
        10,
        60,
        None,
        5,
        "[IU]/L",
        "< 5 [IU]/L hors grossesse",
        None,
        None,
        "Interprétation selon âge gestationnel et cinétique",
        "Usage labo",
    ),
    # ── SPERMOGRAMME OMS ─────────────────────────────────────────────────────
    _r(
        "SPERM_VOL",
        "Volume sperme",
        "Fertilité masculine",
        "Sperme",
        "Homme",
        15,
        120,
        1.4,
        None,
        "mL",
        "≥ 1,4 mL",
        None,
        None,
        "Volume bas : hypospermie possible",
        "OMS spermogramme",
    ),
    _r(
        "SPERM_CONC",
        "Concentration spermatique",
        "Fertilité masculine",
        "Sperme",
        "Homme",
        15,
        120,
        16,
        None,
        "millions/mL",
        "≥ 16 millions/mL",
        None,
        None,
        "Oligozoospermie si bas",
        "OMS spermogramme",
    ),
    _r(
        "SPERM_TOTAL",
        "Nombre total spermatozoïdes",
        "Fertilité masculine",
        "Sperme",
        "Homme",
        15,
        120,
        39,
        None,
        "millions/éjaculat",
        "≥ 39 millions",
        None,
        None,
        "Interpréter avec volume et concentration",
        "OMS spermogramme",
    ),
    _r(
        "SPERM_MOT_T",
        "Mobilité totale",
        "Fertilité masculine",
        "Sperme",
        "Homme",
        15,
        120,
        42,
        None,
        "%",
        "≥ 42 %",
        None,
        None,
        "Asthénozoospermie si basse",
        "OMS spermogramme",
    ),
    _r(
        "SPERM_MOT_P",
        "Mobilité progressive",
        "Fertilité masculine",
        "Sperme",
        "Homme",
        15,
        120,
        30,
        None,
        "%",
        "≥ 30 %",
        None,
        None,
        "Mobilité progressive insuffisante si basse",
        "OMS spermogramme",
    ),
    _r(
        "SPERM_VITAL",
        "Vitalité",
        "Fertilité masculine",
        "Sperme",
        "Homme",
        15,
        120,
        54,
        None,
        "%",
        "≥ 54 %",
        None,
        None,
        "Nécrozoospermie si basse",
        "OMS spermogramme",
    ),
    _r(
        "SPERM_MORPH",
        "Formes normales",
        "Fertilité masculine",
        "Sperme",
        "Homme",
        15,
        120,
        4,
        None,
        "%",
        "≥ 4 %",
        None,
        None,
        "Tératozoospermie si basse",
        "OMS spermogramme",
    ),
]
