"""Correspondances canoniques prioritaires entre vocabulaires biologiques.

Relie exam_code (catalogue) ↔ test_code (bioref) ↔ analyte_code (data_points /
ReferenceRange / CriticalRange). Les panels (NFS, IONO) sont décomposés en
composants via ``component_of``.
"""

from __future__ import annotations


def _m(
    canonical: str,
    exam: str | None = None,
    test: str | None = None,
    analyte: str | None = None,
    component_of: str | None = None,
    label: str | None = None,
    category: str | None = None,
    specimen: str | None = None,
    unit: str | None = None,
    is_panel: bool = False,
    priority: int = 100,
) -> dict:
    return {
        "canonical_code": canonical,
        "exam_code": exam,
        "test_code": test,
        "analyte_code": analyte,
        "component_of": component_of,
        "label": label,
        "category": category,
        "specimen_type": specimen,
        "unit": unit,
        "is_panel": is_panel,
        "priority": priority,
    }


CODE_MAPPING_SEED: list[dict] = [
    # ── Correspondances simples (exam_code ↔ test_code) ──────────────────────
    _m(
        "GLYC",
        exam="GLYC",
        test="GLU_FAST",
        analyte="GLYC",
        label="Glycémie",
        category="Biochimie",
        unit="g/L",
    ),
    _m(
        "GE",
        exam="GE",
        test="MAL_GE",
        analyte="GE",
        label="Goutte épaisse",
        category="Parasitologie",
    ),
    _m(
        "ASAT",
        exam="ASAT",
        test="AST",
        analyte="ASAT",
        label="ASAT / TGO",
        category="Bilan hépatique",
        unit="UI/L",
    ),
    _m(
        "ALAT",
        exam="ALAT",
        test="ALT",
        analyte="ALAT",
        label="ALAT / TGP",
        category="Bilan hépatique",
        unit="UI/L",
    ),
    _m(
        "UREE",
        exam="UREE",
        test="UREA",
        analyte="UREE",
        label="Urée",
        category="Biochimie rénale",
        unit="g/L",
    ),
    _m("AGHBS", exam="AGHBS", test="HBSAG", analyte="AGHBS", label="Ag HBs", category="Sérologie"),
    _m(
        "URIC",
        exam="URIC",
        test="URIC",
        analyte="URIC",
        label="Acide urique",
        category="Biochimie rénale",
        unit="mg/L",
    ),
    _m("VIH", exam="HIV", test="HIV", analyte="HIV", label="VIH 1/2", category="Sérologie"),
    _m(
        "VDRL",
        exam="VDRL",
        test="VDRL",
        analyte="VDRL",
        label="VDRL",
        category="Sérologie syphilis",
    ),
    _m(
        "TPHA",
        exam="TPHA",
        test="TPHA",
        analyte="TPHA",
        label="TPHA",
        category="Sérologie syphilis",
    ),
    _m(
        "CREAT",
        exam="CREAT",
        test="CREAT",
        analyte="CREAT",
        label="Créatinine",
        category="Biochimie rénale",
        unit="mg/L",
    ),
    _m(
        "CRP",
        exam="CRP",
        test="CRP",
        analyte="CRP",
        label="CRP",
        category="Inflammation",
        unit="mg/L",
    ),
    _m(
        "TG",
        exam="TG",
        test="TG",
        analyte="TG",
        label="Triglycérides",
        category="Bilan lipidique",
        unit="g/L",
    ),
    _m(
        "CHOL",
        exam="CHOL",
        test="CHOL_T",
        analyte="CHOL",
        label="Cholestérol total",
        category="Bilan lipidique",
        unit="g/L",
    ),
    _m(
        "HDL",
        exam="HDL",
        test="HDL",
        analyte="HDL",
        label="HDL-cholestérol",
        category="Bilan lipidique",
        unit="g/L",
    ),
    _m(
        "LDL",
        exam="LDL",
        test="LDL",
        analyte="LDL",
        label="LDL-cholestérol",
        category="Bilan lipidique",
        unit="g/L",
    ),
    _m(
        "HBA1C",
        exam="HBA1C",
        test="HBA1C",
        analyte="HBA1C",
        label="Hémoglobine glyquée",
        category="Diabète",
        unit="%",
    ),
    _m(
        "CALC",
        exam="CALC",
        test="CA",
        analyte="CA",
        label="Calcémie",
        category="Biochimie",
        unit="mmol/L",
    ),
    _m("VS", exam="VS", analyte="VS", label="Vitesse de sédimentation", category="Hématologie"),
    _m(
        "WIDAL",
        exam="WIDAL",
        analyte="WIDAL",
        label="Sérodiagnostic de Widal",
        category="Sérologie",
    ),
    _m("ECBU", exam="ECBU", analyte="ECBU", label="ECBU / uroculture", category="Microbiologie"),
    _m(
        "GRH",
        exam="GRH",
        analyte="GRH",
        label="Groupe sanguin Rhésus",
        category="Immuno-hématologie",
    ),
    _m(
        "ELPHB",
        exam="ELPHB",
        analyte="ELPHB",
        label="Électrophorèse de l'hémoglobine",
        category="Hématologie",
    ),
    # ── Panel NFS + composants ───────────────────────────────────────────────
    _m(
        "NFS",
        exam="NFS",
        label="Numération Formule Sanguine",
        category="Hématologie",
        is_panel=True,
        priority=10,
    ),
    _m(
        "HB",
        test="HB",
        analyte="HGB",
        component_of="NFS",
        label="Hémoglobine",
        category="Hématologie",
        unit="g/dL",
    ),
    _m(
        "HT",
        test="HT",
        analyte="HCT",
        component_of="NFS",
        label="Hématocrite",
        category="Hématologie",
        unit="%",
    ),
    _m(
        "WBC",
        test="WBC",
        analyte="WBC",
        component_of="NFS",
        label="Leucocytes",
        category="Hématologie",
        unit="G/L",
    ),
    _m(
        "PLT",
        test="PLT",
        analyte="PLT",
        component_of="NFS",
        label="Plaquettes",
        category="Hématologie",
        unit="G/L",
    ),
    _m(
        "RBC",
        test="RBC",
        analyte="RBC",
        component_of="NFS",
        label="Globules rouges",
        category="Hématologie",
        unit="T/L",
    ),
    _m(
        "MCV",
        test="MCV",
        analyte="MCV",
        component_of="NFS",
        label="VGM",
        category="Hématologie",
        unit="fL",
    ),
    _m(
        "MCH",
        test="MCH",
        analyte="MCH",
        component_of="NFS",
        label="TCMH",
        category="Hématologie",
        unit="pg",
    ),
    _m(
        "MCHC",
        test="MCHC",
        analyte="MCHC",
        component_of="NFS",
        label="CCMH",
        category="Hématologie",
        unit="g/dL",
    ),
    _m(
        "NEUT_PCT",
        test="NEUT_PCT",
        analyte="NEUT_PCT",
        component_of="NFS",
        label="Neutrophiles",
        category="Formule leucocytaire",
        unit="%",
    ),
    _m(
        "LYMPH_PCT",
        test="LYMPH_PCT",
        analyte="LYMPH_PCT",
        component_of="NFS",
        label="Lymphocytes",
        category="Formule leucocytaire",
        unit="%",
    ),
    _m(
        "MONO_PCT",
        test="MONO_PCT",
        analyte="MONO_PCT",
        component_of="NFS",
        label="Monocytes",
        category="Formule leucocytaire",
        unit="%",
    ),
    _m(
        "EOS_PCT",
        test="EOS_PCT",
        analyte="EOS_PCT",
        component_of="NFS",
        label="Éosinophiles",
        category="Formule leucocytaire",
        unit="%",
    ),
    _m(
        "BASO_PCT",
        test="BASO_PCT",
        analyte="BASO_PCT",
        component_of="NFS",
        label="Basophiles",
        category="Formule leucocytaire",
        unit="%",
    ),
    # ── Panel IONO + composants ──────────────────────────────────────────────
    _m(
        "IONO",
        exam="IONO",
        label="Ionogramme sanguin",
        category="Ionogramme",
        is_panel=True,
        priority=10,
    ),
    _m(
        "NA",
        test="NA",
        analyte="NA",
        component_of="IONO",
        label="Sodium",
        category="Ionogramme",
        unit="mmol/L",
    ),
    _m(
        "K",
        test="K",
        analyte="K",
        component_of="IONO",
        label="Potassium",
        category="Ionogramme",
        unit="mmol/L",
    ),
    _m(
        "CL",
        test="CL",
        analyte="CL",
        component_of="IONO",
        label="Chlore",
        category="Ionogramme",
        unit="mmol/L",
    ),
    _m(
        "CA",
        test="CA",
        analyte="CA",
        component_of="IONO",
        label="Calcium total",
        category="Ionogramme",
        unit="mmol/L",
    ),
    _m(
        "MG",
        test="MG",
        analyte="MG",
        component_of="IONO",
        label="Magnésium",
        category="Ionogramme",
        unit="mmol/L",
    ),
    # ── Tests bioref simples sans exam catalogue dédié ──────────────────────
    _m("ALB", test="ALB", analyte="ALB", label="Albumine", category="Biochimie", unit="g/L"),
    _m(
        "ALP",
        test="ALP",
        analyte="ALP",
        label="Phosphatases alcalines",
        category="Bilan hépatique",
        unit="UI/L",
    ),
    _m("GGT", test="GGT", analyte="GGT", label="Gamma-GT", category="Bilan hépatique", unit="UI/L"),
    _m("BILT", test="BILT", analyte="BILT", label="Bilirubine totale", category="Bilan hépatique"),
    _m("BILD", test="BILD", analyte="BILD", label="Bilirubine directe", category="Bilan hépatique"),
    _m(
        "TPROT",
        test="TPROT",
        analyte="TPROT",
        label="Protéines totales",
        category="Biochimie",
        unit="g/L",
    ),
    _m("EGFR", test="EGFR", analyte="EGFR", label="DFG estimé", category="Biochimie rénale"),
    _m(
        "GLU_PP",
        test="GLU_PP",
        analyte="GLU_PP",
        label="Glycémie post-prandiale",
        category="Diabète",
        unit="g/L",
    ),
    _m("HCV_AB", test="HCV_AB", analyte="HCV_AB", label="Ac anti-VHC", category="Sérologie"),
    _m(
        "MAL_TDR",
        test="MAL_TDR",
        analyte="MAL_TDR",
        label="TDR paludisme",
        category="Parasitologie",
    ),
    _m(
        "BHCG_QUAL",
        test="BHCG_QUAL",
        analyte="BHCG_QUAL",
        label="β-HCG qualitatif",
        category="Hormonologie",
    ),
    _m(
        "BHCG_QUANT",
        test="BHCG_QUANT",
        analyte="BHCG_QUANT",
        label="β-HCG quantitatif",
        category="Hormonologie",
    ),
    _m("PT", test="PT", analyte="PT", label="Taux de prothrombine", category="Hémostase"),
    _m("INR", test="INR", analyte="INR", label="INR", category="Hémostase"),
    _m("APTT", test="APTT", analyte="APTT", label="TCA / APTT", category="Hémostase"),
    _m("FIB", test="FIB", analyte="FIB", label="Fibrinogène", category="Hémostase"),
    _m(
        "RBC_H",
        test="RBC_H",
        analyte="RBC_H",
        label="Globules rouges homme",
        category="Hématologie",
        unit="T/L",
    ),
    _m(
        "RBC_F",
        test="RBC_F",
        analyte="RBC_F",
        label="Globules rouges femme",
        category="Hématologie",
        unit="T/L",
    ),
    _m(
        "URIC_H",
        test="URIC_H",
        analyte="URIC_H",
        label="Acide urique homme",
        category="Biochimie rénale",
        unit="mg/L",
    ),
    _m(
        "URIC_F",
        test="URIC_F",
        analyte="URIC_F",
        label="Acide urique femme",
        category="Biochimie rénale",
        unit="mg/L",
    ),
    _m(
        "SPERM_VOL",
        test="SPERM_VOL",
        analyte="SPERM_VOL",
        label="Volume spermatique",
        category="Spermogramme",
    ),
    _m(
        "SPERM_CONC",
        test="SPERM_CONC",
        analyte="SPERM_CONC",
        label="Concentration spermatique",
        category="Spermogramme",
    ),
    _m(
        "SPERM_TOTAL",
        test="SPERM_TOTAL",
        analyte="SPERM_TOTAL",
        label="Nombre total spermatozoïdes",
        category="Spermogramme",
    ),
    _m(
        "SPERM_MOT_T",
        test="SPERM_MOT_T",
        analyte="SPERM_MOT_T",
        label="Mobilité totale",
        category="Spermogramme",
    ),
    _m(
        "SPERM_MOT_P",
        test="SPERM_MOT_P",
        analyte="SPERM_MOT_P",
        label="Mobilité progressive",
        category="Spermogramme",
    ),
    _m(
        "SPERM_VITAL",
        test="SPERM_VITAL",
        analyte="SPERM_VITAL",
        label="Vitalité spermatique",
        category="Spermogramme",
    ),
    _m(
        "SPERM_MORPH",
        test="SPERM_MORPH",
        analyte="SPERM_MORPH",
        label="Morphologie spermatique",
        category="Spermogramme",
    ),
]
