"""Correspondances canoniques prioritaires entre vocabulaires biologiques.

Relie exam_code (catalogue) ↔ test_code (bioref) ↔ analyte_code (data_points /
ReferenceRange / CriticalRange). Les panels (NFS, IONO) sont décomposés en
composants via ``component_of``.
"""

from __future__ import annotations


def _m(
    canonical: str,
    exam: str | None = None,
    test: str | None = None,
    analyte: str | None = None,
    component_of: str | None = None,
    label: str | None = None,
    category: str | None = None,
    specimen: str | None = None,
    unit: str | None = None,
    is_panel: bool = False,
    priority: int = 100,
) -> dict:
    return {
        "canonical_code": canonical,
        "exam_code": exam,
        "test_code": test,
        "analyte_code": analyte,
        "component_of": component_of,
        "label": label,
        "category": category,
        "specimen_type": specimen,
        "unit": unit,
        "is_panel": is_panel,
        "priority": priority,
    }


CODE_MAPPING_SEED: list[dict] = [
    # ── Correspondances simples (exam_code ↔ test_code) ──────────────────────
    _m(
        "GLYC",
        exam="GLYC",
        test="GLU_FAST",
        analyte="GLYC",
        label="Glycémie",
        category="Biochimie",
        unit="g/L",
    ),
    _m(
        "GE",
        exam="GE",
        test="MAL_GE",
        analyte="GE",
        label="Goutte épaisse",
        category="Parasitologie",
    ),
    _m(
        "ASAT",
        exam="ASAT",
        test="AST",
        analyte="ASAT",
        label="ASAT / TGO",
        category="Bilan hépatique",
        unit="UI/L",
    ),
    _m(
        "ALAT",
        exam="ALAT",
        test="ALT",
        analyte="ALAT",
        label="ALAT / TGP",
        category="Bilan hépatique",
        unit="UI/L",
    ),
    _m(
        "UREE",
        exam="UREE",
        test="UREA",
        analyte="UREE",
        label="Urée",
        category="Biochimie rénale",
        unit="g/L",
    ),
    _m("AGHBS", exam="AGHBS", test="HBSAG", analyte="AGHBS", label="Ag HBs", category="Sérologie"),
    _m(
        "URIC",
        exam="URIC",
        test="URIC",
        analyte="URIC",
        label="Acide urique",
        category="Biochimie rénale",
        unit="mg/L",
    ),
    _m("VIH", exam="HIV", test="HIV", analyte="HIV", label="VIH 1/2", category="Sérologie"),
    _m(
        "VDRL",
        exam="VDRL",
        test="VDRL",
        analyte="VDRL",
        label="VDRL",
        category="Sérologie syphilis",
    ),
    _m(
        "TPHA",
        exam="TPHA",
        test="TPHA",
        analyte="TPHA",
        label="TPHA",
        category="Sérologie syphilis",
    ),
    _m(
        "CREAT",
        exam="CREAT",
        test="CREAT",
        analyte="CREAT",
        label="Créatinine",
        category="Biochimie rénale",
        unit="mg/L",
    ),
    _m(
        "CRP",
        exam="CRP",
        test="CRP",
        analyte="CRP",
        label="CRP",
        category="Inflammation",
        unit="mg/L",
    ),
    _m(
        "TG",
        exam="TG",
        test="TG",
        analyte="TG",
        label="Triglycérides",
        category="Bilan lipidique",
        unit="g/L",
    ),
    _m(
        "CHOL",
        exam="CHOL",
        test="CHOL_T",
        analyte="CHOL",
        label="Cholestérol total",
        category="Bilan lipidique",
        unit="g/L",
    ),
    _m(
        "HDL",
        exam="HDL",
        test="HDL",
        analyte="HDL",
        label="HDL-cholestérol",
        category="Bilan lipidique",
        unit="g/L",
    ),
    _m(
        "LDL",
        exam="LDL",
        test="LDL",
        analyte="LDL",
        label="LDL-cholestérol",
        category="Bilan lipidique",
        unit="g/L",
    ),
    # ── Panel NFS + composants ───────────────────────────────────────────────
    _m(
        "NFS",
        exam="NFS",
        label="Numération Formule Sanguine",
        category="Hématologie",
        is_panel=True,
        priority=10,
    ),
    _m(
        "HB",
        test="HB",
        analyte="HGB",
        component_of="NFS",
        label="Hémoglobine",
        category="Hématologie",
        unit="g/dL",
    ),
    _m(
        "HT",
        test="HT",
        analyte="HCT",
        component_of="NFS",
        label="Hématocrite",
        category="Hématologie",
        unit="%",
    ),
    _m(
        "WBC",
        test="WBC",
        analyte="WBC",
        component_of="NFS",
        label="Leucocytes",
        category="Hématologie",
        unit="G/L",
    ),
    _m(
        "PLT",
        test="PLT",
        analyte="PLT",
        component_of="NFS",
        label="Plaquettes",
        category="Hématologie",
        unit="G/L",
    ),
    _m(
        "RBC",
        test="RBC",
        analyte="RBC",
        component_of="NFS",
        label="Globules rouges",
        category="Hématologie",
        unit="T/L",
    ),
    _m(
        "MCV",
        test="MCV",
        analyte="MCV",
        component_of="NFS",
        label="VGM",
        category="Hématologie",
        unit="fL",
    ),
    _m(
        "MCH",
        test="MCH",
        analyte="MCH",
        component_of="NFS",
        label="TCMH",
        category="Hématologie",
        unit="pg",
    ),
    _m(
        "MCHC",
        test="MCHC",
        analyte="MCHC",
        component_of="NFS",
        label="CCMH",
        category="Hématologie",
        unit="g/dL",
    ),
    # ── Panel IONO + composants ──────────────────────────────────────────────
    _m(
        "IONO",
        exam="IONO",
        label="Ionogramme sanguin",
        category="Ionogramme",
        is_panel=True,
        priority=10,
    ),
    _m(
        "NA",
        test="NA",
        analyte="NA",
        component_of="IONO",
        label="Sodium",
        category="Ionogramme",
        unit="mmol/L",
    ),
    _m(
        "K",
        test="K",
        analyte="K",
        component_of="IONO",
        label="Potassium",
        category="Ionogramme",
        unit="mmol/L",
    ),
    _m(
        "CL",
        test="CL",
        analyte="CL",
        component_of="IONO",
        label="Chlore",
        category="Ionogramme",
        unit="mmol/L",
    ),
    _m(
        "CA",
        test="CA",
        analyte="CA",
        component_of="IONO",
        label="Calcium total",
        category="Ionogramme",
        unit="mmol/L",
    ),
    _m(
        "MG",
        test="MG",
        analyte="MG",
        component_of="IONO",
        label="Magnésium",
        category="Ionogramme",
        unit="mmol/L",
    ),
]
